project_id = "grdgjhkygzciwwrxgvgy"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
port = 54327

[auth]
enabled = true
port = 54328

[rest]
enabled = true
port = 54329

[realtime]
enabled = true
port = 54330

[functions.translate-text]
verify_jwt = false

[functions.send-team-invitation]
verify_jwt = true

[functions.create-checkout]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.send-password-reset]
verify_jwt = false

[functions.stripe-connect-onboard]
verify_jwt = true

[functions.stripe-connect-refresh]
verify_jwt = true

[functions.stripe-connect-login]
verify_jwt = true

[functions.create-booking-payment]
verify_jwt = false

[functions.stripe-connect-embedded]
verify_jwt = true

[functions.stripe-connect-reset]
verify_jwt = true

[functions.sync-payment-methods]
verify_jwt = true

[functions.create-service-type-with-stripe]
verify_jwt = true

[functions.whatsapp-payment-handler]
verify_jwt = false

[functions.get-tax-data]
verify_jwt = true

[functions.generate-tax-report]
verify_jwt = true