
project_id = "grdgjhkygzciwwrxgvgy"

[functions.translate-text]
verify_jwt = false

[functions.send-team-invitation]
verify_jwt = true

[functions.create-checkout]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true
