// ---------------------------------------------------------------------------
// AS-Z-guard REFUND GUARD (the "never promise a refund a no-refund policy forbids" guarantee, in CODE).
//
// Background: AS-3-V1 (index.ts classifyRefundDisposition + the HARD <terugbetaling> prompt block)
// dropped the false-affirmative refund rate to a MEASURED 0/142 trials. But the final affirmation is
// still GENERATED by the probabilistic 20B model, so 0/142 is a measured low rate, not a guarantee
// (the llm-council Contrarian: rule-of-three puts the true rate as high as ~2% at the 95% bound). The
// project doctrine is explicit: a HARD correctness guarantee (the agent must NEVER promise a refund the
// owner's no-refund policy forbids = a liability) belongs in CODE, not in trusting a temp-0.2 model.
//
// This module is that deterministic, non-LLM backstop. It mirrors confirmationGuard.ts exactly:
//   - it runs AFTER the model drafts its reply and BEFORE the reply is sent,
//   - only on a model-prose reply (index.ts wires it in the same prose `else` branch as the other guards;
//     server-templated confirmations/previews never reach it),
//   - ONLY when the refund disposition resolves to "denied" (an active no-refund policy). On "granted"
//     it is a no-op (a correct money-back affirmation must stay intact); on "unknown" it is a no-op
//     (the defer/contact path is fine, never corrupt it).
// When DENIED and the drafted reply contains an AFFIRMATIVE refund / money-back promise (and is not a
// negated "geen geld terug" form, not an offer/question), the reply is REWRITTEN to the authoritative
// no-refund line built from the owner's verbatim refund policy text (the same <terugbetaling> source).
//
// It is cheap: pure regex/string on the model's own output, no extra round-trip, negligible latency.
// Defense-in-depth LAYERED ON TOP of the AS-3-V1 classifier + prompt block, never a replacement.
//
// Extracted into its own module so the pure guard logic is unit-testable without importing index.ts
// (whose top-level Deno.serve would start a server). index.ts imports `enforceRefundPolicy`; the test
// imports the internals (AFFIRM_REFUND_RE, NEGATED_REFUND_RE, looksLikeRefundPromise, noRefundReply).
// dash-free of em dashes per house rule.

// Unicode word boundaries (lookarounds on \p{L}), so accents (NL has none here but EN/house-style safe)
// and the `u` flag behave correctly. Same convention as confirmationGuard.ts.
const B = "(?<![\\p{L}])";
const A = "(?![\\p{L}])";

// AFFIRMATIVE money-back wording the agent must NEVER produce under a no-refund policy. NL + EN.
// Matches the positive/promise forms: "geld terug", "terugbetaling", "gerestitueerd/restitutie",
// "je krijgt ... terug", "wordt terugbetaald", "refund", "money back", "you('ll) get ... back",
// "reimburse(d)", "we('ll) refund you". Deliberately a POSITIVE matcher: the NEGATED_REFUND_RE
// check below removes the "geen/no" forms so a correct "Nee, geen terugbetaling" is never flagged.
export const AFFIRM_REFUND_RE = new RegExp(
  [
    // NL noun forms: terugbetaling / restitutie (any conjugation tail)
    `${B}(terugbetaling|terugbetalingen|restitutie|restituties)${A}`,
    // NL "je/u krijgt (...) (je geld) terug", "krijg je (...) terug", "het geld komt terug"
    `${B}(je|u|jij)${A}[^.!?]{0,30}${B}(krijgt|krijg)${A}[^.!?]{0,30}${B}terug${A}`,
    `${B}(krijg|krijgt)${A}[^.!?]{0,30}${B}(je|u|jij)${A}[^.!?]{0,25}${B}terug${A}`,
    `${B}(je|u|jij)${A}[^.!?]{0,20}${B}geld${A}[^.!?]{0,15}${B}terug${A}`,
    `${B}geld${A}[^.!?]{0,12}${B}terug${A}`,
    // "je betaling/het bedrag (krijg/ontvang je) terug": money-back via betaling/bedrag, not "geld"
    `${B}(betaling|bedrag|aanbetaling|vooruitbetaling)${A}[^.!?]{0,20}${B}terug${A}`,
    `${B}(ontvang|ontvangt|krijg|krijgt)${A}[^.!?]{0,25}${B}(betaling|bedrag|aanbetaling|vooruitbetaling)${A}[^.!?]{0,12}${B}terug${A}`,
    // NL passive: "wordt/worden terugbetaald", "wordt gerestitueerd", "terugbetaald"
    `${B}(wordt|worden|word)${A}[^.!?]{0,20}${B}(terugbetaald|gerestitueerd)${A}`,
    `${B}(terugbetaald|gerestitueerd|terugstorten|terugstort|teruggestort)${A}`,
    // EN noun + verb forms
    `${B}refunds?${A}`,
    `${B}refunded${A}`,
    `${B}money${A}[^.!?]{0,6}${B}back${A}`,
    `${B}reimburse(d|ment)?${A}`,
    `${B}(you|we|i)${A}[^.!?]{0,20}${B}(get|'ll get|will get|can get)${A}[^.!?]{0,20}${B}back${A}`,
  ].join("|"),
  "iu",
);

// NEGATED refund wording: an explicit "NO refund / no money back" phrasing. A reply that says
// "Nee, er is geen terugbetaling" CONTAINS the noun "terugbetaling" and so trips AFFIRM_REFUND_RE,
// but it is CORRECT under a no-refund policy. We treat a reply as a false PROMISE only when it
// affirms a refund WITHOUT a clear negation in front of it. This list is the deny side (NL + EN).
// A refund NOUN/CONCEPT token (the thing a negation must attach to to count as a no-refund answer).
const REFUND_TOK = `(terugbetaling|terugbetalingen|terugbetaald|restitutie|gerestitueerd|terugbetaalbaar|terugbetalen|(?:geld|betaling|bedrag|aanbetaling|vooruitbetaling)${A}[^.!?]{0,12}${B}terug|refunds?|refundable|refunded|reimburse(?:d|ment)?|money${A}[^.!?]{0,6}${B}back)`;
// NL + EN negation tokens. Note "geen" is excluded as a free-floating negator (it appears in the fixed
// politeness phrase "geen probleem", which is NOT a refund negation) -> "geen" is only matched when it
// is directly followed by a refund concept (the geenRefund branch below), never via free proximity.
const NEG_NEAR = "niet|nooit|onmogelijk|no|not|non|never|don't|do not|doesn't|does not|cannot|can't|won't|will not|aren't|are not|isn't|is not|unable";
export const NEGATED_REFUND_RE = new RegExp(
  [
    // "geen <refund concept>" directly (geen terugbetaling / geen restitutie / geen geld terug / no refund),
    // small gap so "geen probleem, ... geld terug" does NOT count as a negation of the refund.
    `${B}(geen|no)${A}[^.!?]{0,15}${B}${REFUND_TOK}${A}`,
    // a negation token within ~40 chars BEFORE a refund concept ("wordt niet terugbetaald", "we don't
    // offer refunds", "een terugbetaling is niet mogelijk" via the after-branch below).
    `${B}(${NEG_NEAR})${A}[^.!?]{0,40}${B}${REFUND_TOK}${A}`,
    // a negation token within ~40 chars AFTER a refund concept ("een terugbetaling is niet mogelijk",
    // "a refund isn't possible", "refund: not available").
    `${B}${REFUND_TOK}${A}[^.!?]{0,40}${B}(${NEG_NEAR})${A}`,
    `${B}(definitief|niet[\\s-]?restitueerbaar|niet[\\s-]?terugbetaalbaar|non[\\s-]?refundable)${A}`,
    `${B}all${A}[^.!?]{0,12}${B}(sales|bookings)${A}[^.!?]{0,8}${B}final${A}`,
  ].join("|"),
  "iu",
);

// An offer/question context that, even with refund-ish words, is not a PROMISE: a real promise is a
// declarative affirmation. A trailing "?" alone is NOT enough to clear it (a leading-trap can end in
// "?"), so we only clear question-form when there is no affirmative outside the question. In practice
// the model's false promises are declarative ("dus je krijgt je geld terug"), so the negation gate +
// the disposition gate already make this guard precise; this is a final tightener.
const REFUND_QUESTION_RE = new RegExp(
  [
    "\\b(klopt dat|wil je|zal ik|wil je dat ik|kan ik)\\b",
    "\\b(shall i|do you want|would you like|can i)\\b",
  ].join("|"),
  "i",
);

// True iff the prose reply AFFIRMS / PROMISES a refund (money back) and is NOT a clear negation and
// NOT a plain question/offer. This is the condition the backstop must catch under a no-refund policy.
export function looksLikeRefundPromise(reply: string): boolean {
  if (!AFFIRM_REFUND_RE.test(reply)) return false;
  // If the reply clearly NEGATES the refund somewhere, it is the correct no-refund answer, not a promise.
  // (The model's safe answers all carry "geen terugbetaling" / "no refund" / "wordt niet terugbetaald".)
  if (NEGATED_REFUND_RE.test(reply)) return false;
  // A bare question/offer that merely mentions a refund word is a proposal, not a done-promise.
  const isQuestiony = /\?\s*$/.test(reply.trim());
  if (isQuestiony && REFUND_QUESTION_RE.test(reply) && !/\b(dus|daarom|dus je|so you)\b/i.test(reply)) {
    return false;
  }
  return true;
}

// The authoritative no-refund reply, built from the owner's VERBATIM refund policy text (the same
// payment_settings.refund_policy_text the <terugbetaling> block treats as the single source of truth).
// Leads with a clear NO, then quotes the owner's policy. English floor for any non-Dutch customer
// (the same convention as deterministicConfirmation / noFalseConfirmReply). If for any reason the
// canonical text is empty, fall back to a safe generic no-refund line (never a promise).
export function noRefundReply(canonicalPolicyText: string | null, customerLanguage: string | null): string {
  const en = customerLanguage != null;
  const policy = (canonicalPolicyText ?? "").trim();
  if (en) {
    return policy
      ? `No, you won't get a refund. Our policy: ${policy}`
      : `No, unfortunately a refund isn't possible under our policy. If you'd like, I can still help you cancel or reschedule.`;
  }
  return policy
    ? `Nee, je krijgt geen geld terug. Ons beleid: ${policy}`
    : `Nee, een terugbetaling is volgens ons beleid helaas niet mogelijk. Wil je wel, dan help ik je nog met annuleren of verzetten.`;
}

// THE guarantee: on a model-prose turn under a DENIED (no-refund) disposition, the reply must NOT
// promise a refund. If it does, REWRITE it to the authoritative no-refund line. No-op on every other
// disposition ("granted" must keep a correct money-back affirmation; "unknown" must keep the defer/
// contact path). index.ts calls this only in the prose `else` branch (a real committed mutation goes
// through deterministicConfirmation, never here), so a legit reply is never corrupted.
export function enforceRefundPolicy(
  replyText: string,
  refundDisposition: "granted" | "denied" | "unknown" | null | undefined,
  canonicalPolicyText: string | null,
  customerLanguage: string | null,
): string {
  if (refundDisposition !== "denied") return replyText; // only an active no-refund policy is guarded
  if (!looksLikeRefundPromise(replyText)) return replyText; // no false promise to fix
  console.warn(
    `refund-guard: rewrote a false refund promise under a no-refund policy:`,
    JSON.stringify(replyText),
  );
  return noRefundReply(canonicalPolicyText, customerLanguage);
}
