// E-4: pure presentation layer for the reminder engine. Split out of index.ts so it can be
// unit-tested without importing the function's top-level serve() side effect. The NL/EN
// branch is keyed off the booking locale (bookings.customer_locale, normalised to nl|en by
// the RPC), so an NL booking gets an NL body and an EN booking gets an EN body.

export type ReminderLocale = "nl" | "en";

// SEQP1R16 (P1-3 / finding R15-1): render BOTH the date and the time from a SINGLE zoned
// Intl.DateTimeFormat in the SAME timeZone (Europe/Amsterdam by default, i.e. the timezone the
// time was already localised to). The previous version localised only the TIME to Amsterdam but
// built the DATE from d.getDay()/getDate()/getMonth()/getFullYear(), which read the PROCESS
// timezone (UTC on the Supabase edge runtime). For an appointment in the 00:00-01:59 Amsterdam
// window (its Amsterdam calendar date differs from its UTC date) that rendered the date one day
// early (e.g. Amsterdam Tuesday 7 July 00:30 shown as "maandag 6 juli 2026") while the time was
// correct: an internally contradictory, no-show-causing reminder. Deriving date AND time from the
// same formatter's parts (one instant, one zone) means they can never disagree again. The
// nl-NL/en-US "weekday d month yyyy" word order is assembled explicitly from formatToParts so the
// output shape (Dutch lowercase weekday+month names, no comma) is stable regardless of the
// locale's default date pattern.
export function formatDate(iso: string, locale: ReminderLocale, tz = "Europe/Amsterdam"): { datum: string; tijd: string } {
  try {
    const d = new Date(iso);
    if (isNaN(d.getTime())) return { datum: iso, tijd: "" };
    const tag = locale === "en" ? "en-US" : "nl-NL";
    const dateFmt = new Intl.DateTimeFormat(tag, {
      weekday: "long", day: "numeric", month: "long", year: "numeric", timeZone: tz,
    });
    const parts = dateFmt.formatToParts(d);
    const get = (type: Intl.DateTimeFormatPartTypes) => parts.find((p) => p.type === type)?.value ?? "";
    // Fixed "weekday day month year" order in the SAME Amsterdam zone as the time below.
    const datum = `${get("weekday")} ${get("day")} ${get("month")} ${get("year")}`.trim();
    const tijd = new Intl.DateTimeFormat(tag, { hour: "2-digit", minute: "2-digit", hour12: false, timeZone: tz }).format(d);
    return { datum, tijd };
  } catch {
    return { datum: iso, tijd: "" };
  }
}

// SEQP1R19 (finding R18-2, SECURITY): output-encode every user/owner-controlled string at the
// email-HTML render boundary. reminderHtml interpolates customer_name, business_name and service
// straight into an HTML string; customer_name arrives verbatim from the WhatsApp booking path
// (only the web create-booking path strips <>), so a stored `<img src=x onerror=...>` name (or a
// business_name like `</td></tr><script>...`) rendered as live markup inside a DKIM-signed
// reminder email. Escaping the five HTML-significant characters at this single choke point neutralises
// the injection for every channel and every write path, regardless of what upstream stored. `&` is
// escaped FIRST so an already-safe entity is never double-escaped incorrectly. The plain-text values
// that flow into the SUBJECT (business_name) are escaped the same way; email clients render the
// subject as text, so the entity form (e.g. `&amp;`) is the correct, non-executable representation.
function escapeHtml(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

export function reminderHtml(locale: ReminderLocale, rawName: string, rawBusiness: string, rawService: string | null, datum: string, tijd: string, second: boolean): { subject: string; html: string } {
  // Every interpolated user/owner-controlled field is HTML-escaped exactly once, here at the render
  // boundary (R18-2). `datum`/`tijd` are code-generated by formatDate (fixed formatter output, no
  // user input) so they are safe as-is. `name`/`business`/`service` below are the escaped values.
  const name = escapeHtml(rawName ?? "");
  const business = escapeHtml(rawBusiness ?? "");
  const service = rawService != null ? escapeHtml(rawService) : rawService;
  const t = locale === "en"
    ? {
        kop: second ? "See you soon!" : "Reminder for your appointment",
        greet: `Hi ${name || "there"},`,
        intro: "This is a reminder for your upcoming appointment:",
        service: "Service", date: "Date", time: "Time",
        cant: `Can't make it? Please contact ${business} in time to cancel or reschedule.`,
        sentBy: `This reminder was sent on behalf of ${business}.`,
        subject: `Reminder: your appointment at ${business}`,
      }
    : {
        kop: second ? "Tot zo!" : "Herinnering aan je afspraak",
        greet: `Hoi ${name || "daar"},`,
        intro: "Dit is een herinnering aan je aankomende afspraak:",
        service: "Dienst", date: "Datum", time: "Tijd",
        cant: `Kun je niet? Neem dan tijdig contact op met ${business} om te annuleren of te verzetten.`,
        sentBy: `Deze herinnering is verstuurd namens ${business}.`,
        subject: `Herinnering: je afspraak bij ${business}`,
      };
  const html = `<!DOCTYPE html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"></head>
  <body style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;margin:0;padding:0;background:#f8fafc;">
    <div style="max-width:600px;margin:0 auto;background:#fff;">
      <div style="background:linear-gradient(135deg,#10b981,#059669);color:#fff;padding:36px 30px;text-align:center;">
        <h1 style="margin:0;font-size:24px;">${t.kop} ⏰</h1>
        <p style="margin:8px 0 0;opacity:.9;">${business}</p>
      </div>
      <div style="padding:32px 30px;color:#111827;">
        <p>${t.greet}</p>
        <p>${t.intro}</p>
        <table style="width:100%;border-collapse:collapse;margin:20px 0;">
          ${service ? `<tr><td style="padding:8px 0;color:#6b7280;">${t.service}</td><td style="padding:8px 0;font-weight:600;text-align:right;">${service}</td></tr>` : ""}
          <tr><td style="padding:8px 0;color:#6b7280;">${t.date}</td><td style="padding:8px 0;font-weight:600;text-align:right;">${datum}</td></tr>
          <tr><td style="padding:8px 0;color:#6b7280;">${t.time}</td><td style="padding:8px 0;font-weight:600;text-align:right;">${tijd}</td></tr>
        </table>
        <p style="color:#6b7280;font-size:14px;">${t.cant}</p>
      </div>
      <div style="background:#f8fafc;padding:24px 30px;text-align:center;color:#9ca3af;font-size:13px;">
        <p style="margin:0;">${t.sentBy}</p>
      </div>
    </div>
  </body></html>`;
  return { subject: t.subject, html };
}
