
import React from 'react';
import { Users, Euro, Info } from 'lucide-react';
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from '@/components/ui/tooltip';

export function ServiceChartLegend() {
  return (
    <TooltipProvider>
      <div className="flex items-center justify-center gap-8 p-4 bg-muted/40 rounded-xl border border-white/[0.08]">
        <Tooltip>
          <TooltipTrigger asChild>
            <div className="flex items-center gap-3 cursor-help">
              <div className="flex items-center gap-2">
                <Users className="h-4 w-4 text-blue-400" />
                <div className="w-4 h-4 bg-gradient-to-r from-blue-500 to-blue-400 rounded"></div>
              </div>
              <span className="text-sm font-medium text-foreground">Number of Bookings</span>
              <Info className="h-3 w-3 text-muted-foreground" />
            </div>
          </TooltipTrigger>
          <TooltipContent 
            className="max-w-xs bg-popover border border-white/[0.08] text-foreground"
            side="top"
            align="center"
          >
            <p className="text-sm">Total number of bookings for each service. Higher bars indicate more popular services.</p>
          </TooltipContent>
        </Tooltip>
        
        <Tooltip>
          <TooltipTrigger asChild>
            <div className="flex items-center gap-3 cursor-help">
              <div className="flex items-center gap-2">
                <Euro className="h-4 w-4 text-emerald-400" />
                <div className="w-4 h-4 bg-gradient-to-r from-emerald-500 to-emerald-400 rounded"></div>
              </div>
              <span className="text-sm font-medium text-foreground">Revenue (€)</span>
              <Info className="h-3 w-3 text-muted-foreground" />
            </div>
          </TooltipTrigger>
          <TooltipContent 
            className="max-w-xs bg-popover border border-white/[0.08] text-foreground"
            side="top"
            align="center"
          >
            <p className="text-sm">Total revenue generated by each service. Higher bars indicate more profitable services.</p>
          </TooltipContent>
        </Tooltip>
      </div>
    </TooltipProvider>
  );
}
