
import React from 'react';
import { Users, Euro, Info } from 'lucide-react';
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from '@/components/ui/tooltip';

export function ServiceChartLegend() {
  return (
    <TooltipProvider>
      <div className="flex items-center justify-center gap-8 p-4 bg-slate-800/20 rounded-xl border border-slate-700/30">
        <Tooltip>
          <TooltipTrigger asChild>
            <div className="flex items-center gap-3 cursor-help">
              <div className="flex items-center gap-2">
                <Users className="h-4 w-4 text-blue-400" />
                <div className="w-4 h-4 bg-gradient-to-r from-blue-500 to-blue-400 rounded shadow-lg shadow-blue-500/25"></div>
              </div>
              <span className="text-sm font-medium text-slate-300">Aantal Boekingen</span>
              <Info className="h-3 w-3 text-slate-400" />
            </div>
          </TooltipTrigger>
          <TooltipContent 
            className="max-w-xs bg-slate-900/95 border border-blue-500/30 text-slate-100"
            side="top"
            align="center"
          >
            <p className="text-sm">Total number of bookings for each service. Higher bars indicate more popular services.</p>
          </TooltipContent>
        </Tooltip>
        
        <Tooltip>
          <TooltipTrigger asChild>
            <div className="flex items-center gap-3 cursor-help">
              <div className="flex items-center gap-2">
                <Euro className="h-4 w-4 text-emerald-400" />
                <div className="w-4 h-4 bg-gradient-to-r from-emerald-500 to-emerald-400 rounded shadow-lg shadow-emerald-500/25"></div>
              </div>
              <span className="text-sm font-medium text-slate-300">Omzet (€)</span>
              <Info className="h-3 w-3 text-slate-400" />
            </div>
          </TooltipTrigger>
          <TooltipContent 
            className="max-w-xs bg-slate-900/95 border border-emerald-500/30 text-slate-100"
            side="top"
            align="center"
          >
            <p className="text-sm">Total revenue generated by each service. Higher bars indicate more profitable services.</p>
          </TooltipContent>
        </Tooltip>
      </div>
    </TooltipProvider>
  );
}
