// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qzetadfdmsholqyxxfbh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF6ZXRhZGZkbXNob2xxeXh4ZmJoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1MzU1NzMsImV4cCI6MjA2NDExMTU3M30.MAiEMXjhKGURuLqsi2-xi8Sz_gdSdZNlInJrDdlYf5o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);