/**
 * Password Reset Edge Function
 * 
 * IMPORTANT: To fix password reset redirects, update your Supabase Auth configuration:
 * 1. Go to Supabase Dashboard → Authentication → URL Configuration
 * 2. Set Site URL to: https://bookingsassistant.com/reset-password
 *    (This ensures reset links go directly to the reset page, not homepage)
 * 3. Add these Redirect URLs:
 *    - https://bookingsassistant.com/**
 *    - https://preview--real-bookings-assistant.lovable.app/**
 *    - https://real-bookings-assistant.lovable.app/**
 * 4. Remove any old bookingsassistant.lovable.app references
 * 5. Test the flow: Forgot Password → Email → Reset Password page
 * 
 * The redirectTo parameter in generateLink is often ignored in favor of the Site URL.
 */

import { serve } from "https://deno.land/std@0.190.0/http/server.ts";
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.39.3';
import { Resend } from "npm:resend@2.0.0";

const supabaseUrl = Deno.env.get('SUPABASE_URL')!;
const supabaseServiceKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
const supabase = createClient(supabaseUrl, supabaseServiceKey);

const resend = new Resend(Deno.env.get("RESEND_API_KEY"));

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

interface PasswordResetRequest {
  email: string;
  redirectTo?: string;
}

const handler = async (req: Request): Promise<Response> => {
  // Handle CORS preflight requests
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  if (req.method !== 'POST') {
    return new Response(JSON.stringify({ error: 'Method not allowed' }), {
      status: 405,
      headers: { "Content-Type": "application/json", ...corsHeaders },
    });
  }

  try {
    const { email, redirectTo }: PasswordResetRequest = await req.json();

    if (!email || !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)) {
      return new Response(JSON.stringify({ error: 'Valid email address is required' }), {
        status: 400,
        headers: { "Content-Type": "application/json", ...corsHeaders },
      });
    }

    // Determine the correct base URL with fallback logic
    const domains = [
      'https://bookingsassistant.com',
      'https://preview--real-bookings-assistant.lovable.app',
      'https://real-bookings-assistant.lovable.app'
    ];
    
    let baseUrl = redirectTo || 'https://bookingsassistant.com';
    
    // Ensure we're not using the old/wrong domain
    if (baseUrl.includes('bookingsassistant.lovable.app')) {
      console.log("⚠️  Detected old domain in redirectTo, using production domain instead");
      baseUrl = 'https://bookingsassistant.com';
    }
    
    const fullResetUrl = `${baseUrl}/reset-password`;
    
    // Use Supabase's built-in password reset to generate secure tokens
    console.log("🔄 Generating password reset with Supabase for:", email);
    console.log("🌐 Base URL:", baseUrl);
    console.log("🔗 Full reset URL:", fullResetUrl);
    console.log("🔗 Available domains:", domains);
    
    const { data, error: supabaseError } = await supabase.auth.admin.generateLink({
      type: 'recovery',
      email: email,
      options: {
        redirectTo: fullResetUrl
      }
    });

    if (supabaseError) {
      console.error("❌ Supabase password reset error:", supabaseError);
      return new Response(JSON.stringify({ error: supabaseError.message }), {
        status: 400,
        headers: { "Content-Type": "application/json", ...corsHeaders },
      });
    }

    console.log("✅ Supabase generateLink response:", {
      user: data.user?.email,
      hasActionLink: !!data.properties?.action_link,
      actionLinkDomain: data.properties?.action_link ? new URL(data.properties.action_link).origin : 'none'
    });

    // Extract the reset URL with proper tokens
    const resetUrl = data.properties?.action_link;
    if (!resetUrl) {
      console.error("❌ No reset URL generated by Supabase - full response:", JSON.stringify(data, null, 2));
      return new Response(JSON.stringify({ error: 'Failed to generate reset link' }), {
        status: 500,
        headers: { "Content-Type": "application/json", ...corsHeaders },
      });
    }

    console.log("🔗 Generated reset URL:", resetUrl);
    console.log("🔗 Reset URL domain:", new URL(resetUrl).origin);
    console.log("🔗 Reset URL path:", new URL(resetUrl).pathname);
    console.log("🔗 Reset URL hash:", new URL(resetUrl).hash);

    const expiryTime = new Date(Date.now() + 60 * 60 * 1000); // 1 hour from now
    console.log("Sending custom password reset email to:", email);

    const emailResponse = await resend.emails.send({
      from: "BookingsAssistant <business@bookingsassistant.com>",
      to: [email],
      subject: "Reset your BookingsAssistant password",
      html: `
        <!DOCTYPE html>
        <html>
        <head>
          <meta charset="utf-8">
          <meta name="viewport" content="width=device-width, initial-scale=1.0">
          <title>Reset Your Password</title>
        </head>
        <body style="margin: 0; padding: 0; background-color: #f8fafc; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto', 'Oxygen', 'Ubuntu', 'Cantarell', 'Fira Sans', 'Droid Sans', 'Helvetica Neue', sans-serif;">
          <table width="100%" cellpadding="0" cellspacing="0" style="background-color: #f8fafc; padding: 20px 0;">
            <tr>
              <td align="center">
                <table width="600" cellpadding="0" cellspacing="0" style="max-width: 600px; width: 100%; background: white; border-radius: 12px; box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1);">
                  
                  <!-- Header -->
                  <tr>
                    <td style="padding: 40px 40px 30px 40px; text-align: center; border-bottom: 1px solid #e2e8f0;">
                      <img src="https://grdgjhkygzciwwrxgvgy.supabase.co/storage/v1/object/public/lovable-uploads/81803cac-40e1-4777-b914-5ca4e2490468.png" alt="BookingsAssistant" style="height: 60px; margin-bottom: 20px; display: block; margin-left: auto; margin-right: auto;" />
                      <h1 style="color: #1e293b; margin: 0; font-size: 28px; font-weight: 700; line-height: 1.3;">
                        Reset Your Password
                      </h1>
                      <p style="color: #64748b; margin: 16px 0 0 0; font-size: 16px;">
                        We received a request to reset your password
                      </p>
                    </td>
                  </tr>

                  <!-- Main Content -->
                  <tr>
                    <td style="padding: 40px;">
                      <p style="color: #374151; font-size: 16px; line-height: 1.6; margin-bottom: 24px; margin-top: 0;">
                        Hello,
                      </p>
                      
                      <p style="color: #374151; font-size: 16px; line-height: 1.6; margin-bottom: 32px;">
                        We received a request to reset the password for your BookingsAssistant account. Click the button below to reset your password:
                      </p>

                      <!-- Reset Button -->
                      <table width="100%" cellpadding="0" cellspacing="0" style="margin: 32px 0;">
                        <tr>
                          <td align="center">
                            <a href="${resetUrl}" style="display: inline-block; background-color: #2563eb; color: white; padding: 16px 32px; border-radius: 8px; text-decoration: none; font-weight: 600; font-size: 16px;">
                              Reset Your Password
                            </a>
                          </td>
                        </tr>
                      </table>

                      <!-- Alternative Link -->
                      <table width="100%" cellpadding="0" cellspacing="0" style="background: #f8fafc; border-radius: 8px; margin: 24px 0;">
                        <tr>
                          <td style="padding: 20px;">
                            <p style="color: #374151; font-size: 14px; margin: 0 0 12px 0;">
                              If the button doesn't work, copy and paste this link into your browser:
                            </p>
                            <p style="color: #2563eb; font-size: 14px; margin: 0; word-break: break-all;">
                              ${resetUrl}
                            </p>
                          </td>
                        </tr>
                      </table>

                      <!-- Security Info -->
                      <table width="100%" cellpadding="0" cellspacing="0" style="background: #fef3c7; border-left: 4px solid #f59e0b; border-radius: 4px; margin: 24px 0;">
                        <tr>
                          <td style="padding: 16px;">
                            <p style="color: #92400e; font-size: 14px; margin: 0; font-weight: 600;">
                              ⚠️ Important Security Information
                            </p>
                            <ul style="color: #92400e; font-size: 14px; margin: 8px 0 0 0; padding-left: 16px;">
                              <li>This link will expire in 1 hour (at ${expiryTime.toLocaleString()})</li>
                              <li>This link can only be used once</li>
                              <li>If you didn't request this reset, you can safely ignore this email</li>
                            </ul>
                          </td>
                        </tr>
                      </table>

                      <p style="color: #6b7280; font-size: 14px; line-height: 1.6; margin-top: 32px; margin-bottom: 0;">
                        If you didn't request a password reset, please ignore this email. Your password will remain unchanged.
                      </p>
                    </td>
                  </tr>

                  <!-- Footer -->
                  <tr>
                    <td style="border-top: 1px solid #e2e8f0; padding: 24px 40px; text-align: center;">
                      <p style="color: #6b7280; font-size: 12px; margin: 0;">
                        This email was sent by BookingsAssistant. If you have any questions, contact us at business@bookingsassistant.com
                      </p>
                    </td>
                  </tr>
                  
                </table>
              </td>
            </tr>
          </table>
        </body>
        </html>
      `,
    });

    console.log("Password reset email sent successfully:", emailResponse);

    return new Response(JSON.stringify({ 
      success: true, 
      message: 'Password reset email sent successfully' 
    }), {
      status: 200,
      headers: { "Content-Type": "application/json", ...corsHeaders },
    });

  } catch (error: any) {
    console.error("Error in password reset function:", error);
    return new Response(
      JSON.stringify({ error: error.message }),
      {
        status: 500,
        headers: { "Content-Type": "application/json", ...corsHeaders },
      }
    );
  }
};

serve(handler);