import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.50.0';
import { Resend } from 'https://esm.sh/resend@3.2.0';

// Initialize Supabase client with service key for admin operations
const supabaseUrl = Deno.env.get('SUPABASE_URL')!;
const supabaseServiceKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
const supabase = createClient(supabaseUrl, supabaseServiceKey);

// Initialize Resend
const resendApiKey = Deno.env.get('RESEND_API_KEY')!;
const resend = new Resend(resendApiKey);

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

interface PasswordResetRequest {
  email: string;
  redirectTo?: string;
}

const handler = async (req: Request): Promise<Response> => {
  // Handle CORS preflight requests
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    if (req.method !== 'POST') {
      return new Response(JSON.stringify({ error: 'Method not allowed' }), {
        status: 405,
        headers: { "Content-Type": "application/json", ...corsHeaders },
      });
    }

    const { email }: PasswordResetRequest = await req.json();

    if (!email || !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)) {
      return new Response(JSON.stringify({ error: 'Valid email is required' }), {
        status: 400,
        headers: { "Content-Type": "application/json", ...corsHeaders },
      });
    }

    console.log('🔄 Generating password reset with Supabase for:', email);

    // Determine redirect target from APP_ENV, never from request origin
    const ENV = Deno.env.get('APP_ENV') ?? 'prod';
    const ORIGIN_MAP: Record<string, string> = {
      prod: 'https://bookingsassistant.com',
      preview: 'https://preview--real-bookings-assistant.lovable.app',
      local: 'http://localhost:5173',
    };
    const origin = ORIGIN_MAP[ENV] ?? ORIGIN_MAP.prod;
    const redirectTo = `${origin}/reset-password`;

    console.log('[reset] ENV:', ENV);
    console.log('[reset] redirectTo (final):', redirectTo);

    // Generate reset link using Supabase Admin API
    const { data, error } = await supabase.auth.admin.generateLink({
      type: 'recovery',
      email: email,
      options: {
        redirectTo,
      }
    });

    if (error) {
      console.error('❌ Supabase generateLink error:', error);
      return new Response(JSON.stringify({ error: 'Failed to generate reset link' }), {
        status: 500,
        headers: { "Content-Type": "application/json", ...corsHeaders },
      });
    }

    // Normalize the action_link to enforce our desired redirect_to
    const actionLink = data.properties?.action_link;
    if (!actionLink) {
      console.error("❌ No action link generated by Supabase");
      return new Response(JSON.stringify({ error: 'Failed to generate reset link' }), {
        status: 500,
        headers: { "Content-Type": "application/json", ...corsHeaders },
      });
    }

    console.log('[reset] action_link (orig):', actionLink);

    let finalLink = actionLink;
    try {
      const urlObj = new URL(actionLink);
      const sp = new URLSearchParams(urlObj.search);
      sp.set('redirect_to', redirectTo);
      urlObj.search = sp.toString();
      finalLink = urlObj.toString();
    } catch (e) {
      console.warn('⚠️ Failed to normalize action_link redirect_to, using original link', e);
    }

    console.log('[reset] action_link (final):', finalLink);

    // Send email via Resend
    const emailResult = await resend.emails.send({
      from: 'Bookings Assistant <business@bookingsassistant.com>',
      to: email,
      subject: 'Reset Your Password - Bookings Assistant',
      html: `
        <!DOCTYPE html>
        <html>
        <head>
          <meta charset="utf-8">
          <meta name="viewport" content="width=device-width, initial-scale=1.0">
          <title>Password Reset</title>
        </head>
        <body style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; line-height: 1.6; color: #E5E7EB; max-width: 600px; margin: 0 auto; padding: 20px; background-color: #1F2937;">
          
          <div style="background: linear-gradient(135deg, #111827 0%, #1F2937 100%); padding: 30px; text-align: center; border-radius: 12px 12px 0 0; border-bottom: 2px solid #10B981;">
            <h1 style="color: #FFFFFF; margin: 0; font-size: 28px; font-weight: 700;">Bookings Assistant</h1>
            <p style="color: #10B981; margin: 10px 0 0 0; font-size: 14px; text-transform: uppercase; letter-spacing: 1px;">Password Reset Request</p>
          </div>
          
          <div style="background: #111827; padding: 30px; border-radius: 0 0 12px 12px; border: 1px solid #374151; border-top: none;">
            <h2 style="color: #FFFFFF; margin-top: 0; font-size: 22px;">Reset Your Password</h2>
            
            <p style="color: #9CA3AF; font-size: 15px; line-height: 1.7;">
              We received a request to reset your password for your Bookings Assistant account. Click the button below to create a new password.
            </p>
            
            <div style="text-align: center; margin: 35px 0;">
              <a href="${finalLink}" 
                 style="background: linear-gradient(135deg, #10B981 0%, #34D399 100%); 
                        color: #FFFFFF; 
                        padding: 16px 40px; 
                        text-decoration: none; 
                        border-radius: 8px; 
                        font-weight: 600; 
                        display: inline-block;
                        font-size: 16px;
                        box-shadow: 0 4px 14px rgba(16, 185, 129, 0.4);">
                Reset My Password
              </a>
            </div>
            
            <p style="color: #6B7280; font-size: 13px; text-align: center;">
              This link will expire in 1 hour for security reasons.
            </p>
            
            <div style="background: rgba(16, 185, 129, 0.1); border: 1px solid rgba(16, 185, 129, 0.3); padding: 16px; border-radius: 8px; margin: 30px 0;">
              <p style="margin: 0; color: #9CA3AF; font-size: 13px;">
                <strong style="color: #10B981;">Security Notice:</strong> If you didn't request this password reset, please ignore this email. Your password will remain unchanged.
              </p>
            </div>
            
            <div style="border-top: 1px solid #374151; margin-top: 30px; padding-top: 20px;">
              <p style="color: #6B7280; font-size: 12px; margin: 0;">
                If the button doesn't work, copy and paste this link into your browser:
              </p>
              <p style="color: #10B981; font-size: 11px; word-break: break-all; margin: 8px 0 0 0;">
                ${finalLink}
              </p>
            </div>
            
            <div style="text-align: center; margin-top: 30px; padding-top: 20px; border-top: 1px solid #374151;">
              <p style="color: #6B7280; font-size: 12px; margin: 0;">
                © 2025 Bookings Assistant. All rights reserved.
              </p>
            </div>
          </div>
          
        </body>
        </html>
      `
    });

    if (emailResult.error) {
      console.error('❌ Resend email error:', emailResult.error);
      return new Response(JSON.stringify({ error: 'Failed to send email' }), {
        status: 500,
        headers: { "Content-Type": "application/json", ...corsHeaders },
      });
    }

    console.log('✅ Password reset email sent successfully:', emailResult.data);

    return new Response(JSON.stringify({ 
      success: true, 
      message: 'Password reset email sent successfully',
      emailId: emailResult.data?.id 
    }), {
      status: 200,
      headers: { "Content-Type": "application/json", ...corsHeaders },
    });

  } catch (error) {
    console.error('❌ Unexpected error:', error);
    return new Response(JSON.stringify({ error: 'Internal server error' }), {
      status: 500,
      headers: { "Content-Type": "application/json", ...corsHeaders },
    });
  }
};

serve(handler);